name: coiner
description: "A trading simulator with no drawbacks"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.2.1
  go_router: ^17.0.1
  google_fonts: ^8.0.1
  hooks_riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
